name: Unit Tests

on:
  push:
  pull_request:
  schedule:
    - cron: '0 8 * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run unit tests

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Update APT cache
        run: |
          sudo apt-get update

      - name: Get build dependencies
        run: |
          # note: debhelper v13 isn't available from ubuntu-20.04 yet, we need a backport
          sudo apt-add-repository -y ppa:ubuntu-cloud-archive/yoga-staging
          sudo apt-get build-dep -q -y -Ppkg.ngcp-rtpengine.nobcg729 .

      - name: Run unit tests with sanitizers enabled
        run: |
          make asan-check
